# Generated by Django 6.0 on 2025-12-27 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('cor', models.CharField(choices=[('primary', '🔵 Azul'), ('success', '🟢 Verde'), ('danger', '🔴 Vermelho'), ('warning', '🟡 Amarelo'), ('info', '🔵 Ciano'), ('secondary', '⚫ Cinza')], default='primary', max_length=20, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Digite o título da tarefa', max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, help_text='Descreva os detalhes da tarefa (opcional)', verbose_name='Descrição')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('prioridade', models.CharField(choices=[('baixa', '🟢 Baixa'), ('media', '🟡 Média'), ('alta', '🔴 Alta')], default='media', max_length=10, verbose_name='Prioridade')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('data_limite', models.DateField(blank=True, null=True, verbose_name='Data limite')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='tarefas.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-prioridade', '-criada_em'],
            },
        ),
    ]
